### ISSUE TITLE
Angular2

### ISSUE THREAD

**Issue by nitishkumarnitc** [JohnnyTheTank/angular-footballdata-api-factory#2]
How can i use these APIs with angular2? Please help me.

**Comment by JohnnyTheTank** [comment]
this is a angular1 module. it's not usable with ng2 at the moment

**Comment by nitishkumarnitc** [comment]
Are you going to provide the APIs for Angular2 later or is there a way to write it in angular2, as i know only angular2.
Thanks

**Comment by JohnnyTheTank** [comment]
It's not planned to provide this module for ng2. you can easy write your own module for football-data and ng2
